QUESTION_SEED = [
    {
        "question": "What does HTML stand for?",
        "option_a": "Hyper Text Markup Language",
        "option_b": "High Tech Modern Language",
        "option_c": "Hyper Transfer Markup Language",
        "option_d": "Home Tool Markup Language",
        "correct_ans": "a",
        "difficulty": "easy",
        "category": "web",
    },
    {
        "question": "Which language is used for styling web pages?",
        "option_a": "HTML",
        "option_b": "CSS",
        "option_c": "Python",
        "option_d": "Java",
        "correct_ans": "b",
        "difficulty": "easy",
        "category": "web",
    },
    {
        "question": "What does CPU stand for?",
        "option_a": "Central Process Unit",
        "option_b": "Central Processing Unit",
        "option_c": "Computer Personal Unit",
        "option_d": "Central Processor Utility",
        "correct_ans": "b",
        "difficulty": "easy",
        "category": "general",
    },
    {
        "question": "Which of the following is a Python data type?",
        "option_a": "paragraph",
        "option_b": "dictionary",
        "option_c": "module",
        "option_d": "function",
        "correct_ans": "b",
        "difficulty": "easy",
        "category": "python",
    },
    {
        "question": "What symbol is used for comments in Python?",
        "option_a": "//",
        "option_b": "--",
        "option_c": "#",
        "option_d": "/* */",
        "correct_ans": "c",
        "difficulty": "easy",
        "category": "python",
    },
    {
        "question": "What is the output of: print(type(10))?",
        "option_a": "<class 'float'>",
        "option_b": "<class 'int'>",
        "option_c": "<class 'str'>",
        "option_d": "<class 'number'>",
        "correct_ans": "b",
        "difficulty": "medium",
        "category": "python",
    },
    {
        "question": "Which FastAPI feature is commonly used to validate request bodies?",
        "option_a": "Pydantic models",
        "option_b": "Jinja templates",
        "option_c": "Flask blueprints",
        "option_d": "MySQL cursors",
        "correct_ans": "a",
        "difficulty": "medium",
        "category": "api",
    },
    {
        "question": "Which SQL keyword is used to retrieve data from a database?",
        "option_a": "GET",
        "option_b": "FETCH",
        "option_c": "SELECT",
        "option_d": "RETRIEVE",
        "correct_ans": "c",
        "difficulty": "medium",
        "category": "general",
    },
    {
        "question": "What is the default port number commonly used by Uvicorn during local development?",
        "option_a": "8080",
        "option_b": "3000",
        "option_c": "5000",
        "option_d": "8000",
        "correct_ans": "d",
        "difficulty": "medium",
        "category": "api",
    },
    {
        "question": "Which HTTP method is typically used to submit form data?",
        "option_a": "GET",
        "option_b": "POST",
        "option_c": "PUT",
        "option_d": "PATCH",
        "correct_ans": "b",
        "difficulty": "medium",
        "category": "web",
    },
    {
        "question": "What is the time complexity of binary search?",
        "option_a": "O(n)",
        "option_b": "O(n log n)",
        "option_c": "O(log n)",
        "option_d": "O(1)",
        "correct_ans": "c",
        "difficulty": "hard",
        "category": "general",
    },
    {
        "question": "In Python, what does the GIL stand for?",
        "option_a": "Global Interpreter Lock",
        "option_b": "General Input Lock",
        "option_c": "Global Index Loop",
        "option_d": "Generated Interpreter Layer",
        "correct_ans": "a",
        "difficulty": "hard",
        "category": "python",
    },
    {
        "question": "Which data structure uses LIFO (Last In, First Out)?",
        "option_a": "Queue",
        "option_b": "Array",
        "option_c": "Stack",
        "option_d": "Linked List",
        "correct_ans": "c",
        "difficulty": "hard",
        "category": "general",
    },
    {
        "question": "What does the 'yield' keyword do in Python?",
        "option_a": "Stops the function permanently",
        "option_b": "Returns a value and pauses the function",
        "option_c": "Deletes a variable",
        "option_d": "Creates a new thread",
        "correct_ans": "b",
        "difficulty": "hard",
        "category": "python",
    },
    {
        "question": "In SQL, what is the difference between WHERE and HAVING?",
        "option_a": "No difference",
        "option_b": "WHERE filters rows, HAVING filters groups",
        "option_c": "HAVING filters rows, WHERE filters groups",
        "option_d": "WHERE is for UPDATE only",
        "correct_ans": "b",
        "difficulty": "hard",
        "category": "general",
    },
]
